### ISSUE TITLE
frontend/android branch not available but readme state that

### ISSUE THREAD

**Issue by sanjay95** [mosip/inji#1197]
I am trying to run the app in android studio and was following the readme instruction, Readme instructs that `frontend/android` branch can be used to directly run the app in android studio but I am not finding this branch here. 

Is there any change ?
Please update the instructions too .

Also, can you please mention if Inji would work with Open JDK and what version is compatible.

I am sure, OpenJDK would work but I am getting issue 
`startup failed:
npm ERR!   General error during conversion: Unsupported class file major version 65
npm ERR!   
npm ERR!   java.lang.IllegalArgumentException: Unsupported class file major version 65
npm ERR!        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
npm ERR!        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
npm ERR!        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
npm ERR!        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)`

Java verrsion 
`openjdk 21.0.1 2023-10-17
OpenJDK Runtime Environment Homebrew (build 21.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.1, mixed mode, sharing)`

**Comment by abhip2565** [comment]
Can you use java 11 or 17 please?

**Comment by sanchi-singh24** [comment]
Closing this issue due to inactivity.
No updates or responses have been received for a while.
If this is still relevant, please feel free to reopen or create a new issue with the latest details.
