### ISSUE TITLE
Cross platform : sharing is not working 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#548]
**Describe the bug**
Wallet device stuck in "id has been sent" screen, while verifier is stuck In "connected to the device waiting for id"

**To Reproduce**
Prerequisite:

iOS (wallet) --> VC is downloaded and stored
Android (verifier)

**steps:**
1. Scan the qr code from iOS
2. select VC to share
3. click on "Accept request and choose ID" button

**Expected behavior**
The VC should be shared in cross-platform OS, without any errors

**Observed**
Wallet device stuck in "id has been sent" screen, while verifier is stuck In "connected to the device waiting for id", I am attaching the screenshot and the error logs below 

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/217748068-23170397-7379-4dbf-9b13-1b3664114b9c.png)
![image](https://user-images.githubusercontent.com/102220709/217748126-235bd796-bd0d-42df-a44a-99e43044f778.png)

**LOGS**
```failed to decrypt data of size 132697, with exception: mac check in GCM failed, stacktrace: org.bouncycastle.crypto.InvalidCipherTextException: mac check in GCM failed
                                                                                                    	at org.bouncycastle.crypto.modes.GCMBlockCipher.doFinal(Unknown Source:228)
                                                                                                    	at io.mosip.tuvali.cryptography.CipherBoxImpl.process(CipherBoxImpl.java:35)
                                                                                                    	at io.mosip.tuvali.cryptography.CipherBoxImpl.decrypt(CipherBoxImpl.java:28)
                                                                                                    	at io.mosip.tuvali.cryptography.SenderTransfersOwnershipOfData.decryptUponReceive(SenderTransfersOwnershipOfData.java:37)
                                                                                                    	at io.mosip.tuvali.verifier.Verifier.onResponseReceived(Verifier.kt:228)
                                                                                                    	at io.mosip.tuvali.verifier.transfer.TransferHandler.handleMessage(TransferHandler.kt:74)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:201)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:65)```


**Verified in:**
wallet
Device: iPhone 7
OS: 15.6
Inji app version: 0.4.1 (15) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 4.2

verifier
Device: Redmi 6A
OS: Android 9
Inji app version : https://github.com/mosip/inji/actions/runs/4123991786
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 4.2

**Comment by rakhimosip** [comment]
**Tested on** 
iOS(Wallet) - iPhone 14 Promax
Android (Verifier) - Redmi 9i sport

Commit ID: https://github.com/mosip/inji/commit/5fa5c9b3fa97c3492a5cf5eb709a60ae5703ba12

We were able to execute this test case successfully.

**Comment by Alka1703** [comment]
On IOS wallet, we have observed the secrets are getting initialised multiple times. This is because of initialisation is being done on receiving an advertisement. Hence during a normal VC transfer, if there is a possibility of another device advertising can cause re-initialisation of the secrets also which could eventually result in a decryption error (GCM error).

The following PRs would possibly address this issue: 
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/24
PR for mosip/inji: https://github.com/mosip/inji/pull/573

The PRs have been merged in 20-02-2023 Release and the latest commit id on mosip/inji/develop is 6df8076

**Comment by Anushree09-N** [comment]
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

App version: 
![image](https://user-images.githubusercontent.com/79500509/220966559-047985ab-0f99-4ffb-8b53-517edfe162c9.png)

Verified in below device combinations in debug build:
![image](https://user-images.githubusercontent.com/79500509/220966100-da8e4c16-b194-4e89-b431-3eb11431772d.png)

Issue not observed, Will re-verify the ticket in release build.

**Comment by Anuranjan14** [comment]
Tested this issue in the new build with the same combination as above, the issue is still occurring in few combinations, attaching the screenshots below for the reference, hence reopening this bug

screenshot : 
![image](https://user-images.githubusercontent.com/120705365/223121139-fbc2412c-11e1-4ef2-90be-e2409e951d7f.png)

Issue 1 : 
![image](https://user-images.githubusercontent.com/120705365/223121345-e9375131-9549-4f0d-b396-57ee8e0fb888.png)

Issue 2:
![image](https://user-images.githubusercontent.com/120705365/223121745-86b14a0a-2f10-43e0-a9e5-e7dd3214a93e.png)

Issue 3:
https://user-images.githubusercontent.com/120705365/223123847-73b37c8e-318c-4bff-9e9e-554811b1b90e.mp4

- MOSIP Version : 1.2.0.1
- MOSIP server : qa-1201-b2.net
- APP link : https://github.com/mosip/inji/actions/runs/4293687772
- IPA Testflight version : 0.4.1 (21)

**Comment by Sujithbn** [comment]
@krishnakumar4a4 : If this is a duplicate of #525, please close one of the ticket.

**Comment by krishnakumar4a4** [comment]
> Tested this issue in the new build with the same combination as above, the issue is still occurring in few combinations, hence reopening this issue. Attaching the screenshots below for the reference.
> 
> screenshot : ![image](https://user-images.githubusercontent.com/120705365/223121139-fbc2412c-11e1-4ef2-90be-e2409e951d7f.png)
> 
> Issue 1 : ![image](https://user-images.githubusercontent.com/120705365/223121345-e9375131-9549-4f0d-b396-57ee8e0fb888.png)
> 
> Issue 2: ![image](https://user-images.githubusercontent.com/120705365/223121745-86b14a0a-2f10-43e0-a9e5-e7dd3214a93e.png)
> 
> Issue 3: https://user-images.githubusercontent.com/120705365/223123847-73b37c8e-318c-4bff-9e9e-554811b1b90e.mp4
> 
> * MOSIP Version : 1.2.0.1
> * MOSIP server : qa-1201-b2.net
> * APP link : https://github.com/mosip/inji/actions/runs/4293687772
> * IPA Testflight version : 0.4.1 (21)
> 
> CommitId: ![image](https://user-images.githubusercontent.com/120705365/223417209-a58a2cb8-0f82-49d4-b1dd-8409cf6a0f7c.png) ![image](https://user-images.githubusercontent.com/120705365/223417289-bd68ce63-d559-4e50-9197-625e7ae3ebb8.png)

The mentioned devices are tested for VC transfer by the dev team in coordination with QA team. Here are the findings
1. Iphone 11 and Vivo Y73 -> Multiple attempts of VC transfer are working with smaller and larger VCs
2. Iphone 8 and Redmi 7A -> Multiple attempts of VC transfer are working with smaller and larger VCs 
3. Iphone 7 and Redmi 7A -> Multiple attempts of smaller VC transfer works. Larger VC transfer intermittently fails.

Regarding iphone 7 and Redmi 7A larger VC intermittent transfer failure. We have created new github issue with all the details https://github.com/mosip/inji/issues/667. The root cause for the issue turns out to be the default failure frame retry count of 5 is not enough for larger VC size (500KB compressed). 
Hence we need to increase the failure frame retry count to 15 to accommodate this device combination. This enhancement is done as part of https://github.com/mosip/inji/issues/668 and is part of **24-03-2023** release:

INJI PR link: https://github.com/mosip/inji/pull/670
Tuvali PR link: https://github.com/mosip/tuvali/pull/49

**Comment by santhoshsunder** [comment]
We are not seeing the crashing issue while sharing VC on cross platform, verified on Iphone 7,8,11 in combination with android devices (VIVO Y73, Redmi K20 pro, Redmi note 10 lite), hence closing this bug

We have noticed the disconnect popup issue on single device (pixel 6 as verifier) for which we have a separate issue logged #665  

Comite ID : 
![image](https://user-images.githubusercontent.com/102220709/228508313-28c43f6d-7922-4630-b759-9b780a75b415.png)
