### ISSUE TITLE
Android - Specific devices are getting stuck in face auth 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#672]
**Describe the bug**
Specific devices are getting stuck in the face auth while sharing 

**To Reproduce**
Prerequisite: have VC downloaded in the wallet

1. open scanner on wallet
2. open qr code in verifier
3. Select a VC in wallet and click on face auth
4. perform face auth 

**Expected behavior**
The phone should recognize the resident's face and sharing should be successful  

**Actual behavior**
Once the face is captured, the app is stuck in the camera page, its happening in specific device

**Screenshots**
https://user-images.githubusercontent.com/102220709/227864096-1f5acd5e-128c-426b-bea4-d770cbbc7b2a.mp4

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/102220709/227873863-5425d6ef-462c-4172-971b-93c76bf5f8ba.png)

**Smartphone :**
![image](https://user-images.githubusercontent.com/102220709/227876083-dca3362b-ae2e-43b8-a4e2-51444b1282d6.png)
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622

Also, this issue reproduced in 
Device Details:
Device: Samsung A03 core
Android Version : 11
BLE: 4.2

**Comment by tilak-puli** [comment]
FATAL EXCEPTION: main
                                                                                                    Process: io.mosip.residentapp, PID: 17013
                                                                                                    java.lang.IllegalArgumentException: x must be >= 0
                                                                                                    	at android.graphics.Bitmap.checkXYSign(Bitmap.java:435)
                                                                                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:873)
                                                                                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:836)
                                                                                                    	at com.mosipinjifacesdk.MosipInjiFaceSdkModule$1.onSuccess(MosipInjiFaceSdkModule.java:106)
                                                                                                    	at com.mosipinjifacesdk.MosipInjiFaceSdkModule$1.onSuccess(MosipInjiFaceSdkModule.java:98)
                                                                                                    	at com.google.android.gms.tasks.zzn.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7562)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2023-03-27 16:51:16.354 19762-19839 MosipInjiFaceSdk        pid-19762                            D  Inside faceAuth...
2023-03-27 16:51:16.354 19762-19839 MosipInjiFaceSdk        pid-19762                            D  Inside detext facecapturedImage
2023-03-27 16:51:16.678 19762-19839 MosipInjiFaceSdk        pid-19762                            D  Inside detext facevcImage
2023-03-27 16:51:17.800 19762-19762 MosipInjiFaceSdk        pid-19762                            D  no of face detected :: 0
2023-03-27 16:51:17.800 19762-19762 MosipInjiFaceSdk        pid-19762                            E  Exception occurred, no face found in one image

**Comment by vijay151096** [comment]
Handled The Face Auth Stuck Screen Issue. 

Here is the Current flow after handling the Issue.
**Success Flow :**

1. After VC is selected for sharing.
2. click share with selfie
3. Scan the Face.
4. it should Complete the Sharing Successfully.

**Failure Flow :**

1. After VC is selected for sharing.
2. click share with selfie
3. Scan the Face.
4. it should throw a popup saying Face Unrecognised.
5. you can either try again or cancel.
6. if you click try again the steps will loop.
7. and if you click cancel, you can still proceed to share without selfie. and complete the transfer.

<img width="912" alt="Screenshot 2023-03-28 at 6 31 50 PM" src="https://user-images.githubusercontent.com/94220135/228786145-d30b2ebd-abfc-4ad7-a177-361edf26048d.png">

**Comment by Raginikrishnamurthy** [comment]
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/ef2f7422-410f-48ac-bda7-8f4c7e88b4f2)
